### ISSUE TITLE
Re-licence for EnderDustAndMore

### ISSUE THREAD

**Issue by ProxyNeko** [proxysprojects/EnderDustAndMore#1]
@Mohron and @MrIbby do you consent to the license change in EnderDustAndMore from GNU Lesser General Public License v3.0 to the MIT License? If no state your reason/s below and we shall find some middle ground.

**Comment by MrIbby** [comment]
I @MrIbby listed above as @MrIbby consent to the relicensing of my contributions to the Ender Dust and More project under the license as stated in LICENSE.md

**Comment by Mohron** [comment]
I @Mohron listed above as @Mohron consent to the relicensing of my contributions to the Ender Dust and More project under the license as stated in LICENSE.md

**Comment by ProxyNeko** [comment]
I Acknowledge the agreement to change the licence to MIT and lock this ticket. My thanks to both of you.
