### ISSUE TITLE
Curse forge still links to the jar with both embedded files

### ISSUE THREAD

**Issue by kragnoth** [proxysprojects/EnderDustAndMore#1]
Once you upload the new version it'll be fixed, but curse forge still downloads the jar that has ender ores and ender dusts and more.  It shows up as two mods in the mod list, and two items.

**Comment by ProxyNeko** [comment]
Thanks for pointing that out. I think I forgot to remove something so when it compiled it put the old code in from before the refactor so I'll push out a bugfix to remove the old code in a bit :)

**Comment by ProxyNeko** [comment]
Fixed in the latest release either here
https://github.com/proxysprojects/EnderDustAndMore/releases/tag/v1.0.1
or now approved here
https://minecraft.curseforge.com/projects/ender-dust-more/files/2393999
Sorry for the long wait
